import { prisma } from '@/lib/prisma'
import { NextResponse } from 'next/server'

// CLYW colors extracted from yoyorewind.com
const clywColors = [
  { name: "1.21 Gigawatts", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/gnar12_3_600x.webp" },
  { name: "28 Stories", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/cliff14_1_600x.webp" },
  { name: "Adam Brewster", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/chief13_8.webp" },
  { name: "Alec Campbell", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/chief15_3.webp" },
  { name: "Algae Bloom", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/orca12_3.webp" },
  { name: "Aquamarine", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/manatee11_5_b4388e04-1261-4b19-8452-de977bdd754b_600x.webp" },
  { name: "Aquatic Life", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/orca11_3.webp" },
  { name: "Arctic Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/kayak13_1_600x.webp" },
  { name: "Army Green", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/ditch202304_12.jpg" },
  { name: "Ash Berry", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/ge12.webp" },
  { name: "Ash Berry Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/blizzard11_1.webp" },
  { name: "Baby Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/campfire11.jpg" },
  { name: "Base Jump", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/gnar12_2_600x.webp" },
  { name: "Beach Party", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/akita13_600x.webp" },
  { name: "Berry Berry", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/chief15_4.webp" },
  { name: "Berry Melt", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/manatee13_5_572fbb44-0ffd-486b-8140-05c7762a0ae9_600x.webp" },
  { name: "Bip Bop", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/wooly2_18.webp" },
  { name: "Black Bip Bop", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/kodiak11_2_600x.webp" },
  { name: "Black Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/ge11.webp" },
  { name: "Black w. Green Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/sasquatch11_1.webp" },
  { name: "Black w/Pink Speckles", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bonfire19.jpg" },
  { name: "Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/puffin12.webp" },
  { name: "Blueberry Muffin Puffin", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/04/puffin2_19.webp" },
  { name: "Blue Bip Bop", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief14_5.webp" },
  { name: "Blue Cosmos", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/compass14_600x.webp" },
  { name: "Blue Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/bvm2_15_600x.webp" },
  { name: "Blue Thistle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/avalanche12_2_600x.webp" },
  { name: "Bombshell Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/kayak12_1_1_600x.webp" },
  { name: "Bright Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/manatee15_463c4152-b9fb-49c1-b87f-5ed7fe94ca2d_600x.webp" },
  { name: "Bright Green", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/manatee14_1_8bbf205d-016c-4e0a-83ab-223b10609c78_600x.webp" },
  { name: "Broken Twill", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief15_7.webp" },
  { name: "Brussels Sprouts", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief15_10.webp" },
  { name: "Buffalo Bob", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief14_1.webp" },
  { name: "Bunny Hill", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/avalanchi17.webp" },
  { name: "Burnt Orange", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/ac17.webp" },
  { name: "Bushmen", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/gnar15_600x.webp" },
  { name: "Camp Caribou", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/bvm2_13_600x.webp" },
  { name: "Camp Caribou Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/ac2_18.webp" },
  { name: "Campfire Orange", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/boy202012_13_600x.webp" },
  { name: "Canadian Tuxedo", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief15_5.webp" },
  { name: "Chinook Wind", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/igloo15.webp" },
  { name: "CHKNSTRPS", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/boy202112_11.jpg" },
  { name: "Chut Chut", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/gnar11_1_1_600x.webp" },
  { name: "Clareview Splat", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/avalanche16_2_600x.webp" },
  { name: "Clareview Station", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/bvm2-12_600x.webp" },
  { name: "Clareview Station Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/sasquatch15.webp" },
  { name: "City of Champions", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/bvm2_16_600x.webp" },
  { name: "Coffee Splash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/avalanchi11.webp" },
  { name: "Concrete Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief11_7.webp" },
  { name: "Confetti", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/bonfire11_1.webp" },
  { name: "Confetti Cannon", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/borealis14_2_2_600x.webp" },
  { name: "Cool Ghoul", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/chief14_4.webp" },
  { name: "Copper Acidwash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/arcticcircle13_1_1.webp" },
  { name: "Cowboy Ninja Bear", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/gnar17_1_600x.webp" },
  { name: "Crod", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/peak2_11_2_600x.webp" },
  { name: "CRYO", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/05/arcticcircle14_1.webp" },
  { name: "Dandelion", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief15_1.webp" },
  { name: "Death Star", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/orca17_2.webp" },
  { name: "Deep Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/akita202012_12_600x.webp" },
  { name: "Deep Purple", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/12/sasquatch11-deeppurple.jpg" },
  { name: "Delirium Dive", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief13_5.webp" },
  { name: "Delirium Dive Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/cliff11_1_600x.webp" },
  { name: "Desert Rose", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/dune202309_13.jpg" },
  { name: "Dirty Sunset", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief11_12.webp" },
  { name: "Disco Panther", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/scout19_600x.webp" },
  { name: "Dragon Bones", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/avalanchi16.webp" },
  { name: "Dugong", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/manatee11_1_2d3b0e2c-9213-46d0-8e84-a7e04ee60949_600x.webp" },
  { name: "Earth Spin Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/puffin11_3.webp" },
  { name: "Electric Bacon", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/ge13.webp" },
  { name: "Electric Bacon Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief11_14.jpg" },
  { name: "Elliot", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief14_3.webp" },
  { name: "Emerald", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bigdipper11.webp" },
  { name: "Every Berry", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/avalanche11_1_600x.webp" },
  { name: "Every Berry Smoothie", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/orca18_1.webp" },
  { name: "Falcon Jab", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief12_7.webp" },
  { name: "Ferdico Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/puffin13_3.webp" },
  { name: "Fire", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief15.webp" },
  { name: "Fire Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/avalanch15.webp" },
  { name: "Fixin's", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bonfire18_2.webp" },
  { name: "Forest Green", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/ac2_11.webp" },
  { name: "Forever Summer", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/manatee12_3_e5289ba7-329d-4333-a021-cae51b2177bc_600x.webp" },
  { name: "Foxy Moss", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief14.webp" },
  { name: "Frog Belly", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/puffin2_11_3.webp" },
  { name: "Frozen Battery", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/compass16_600x.webp" },
  { name: "Frozen Mammoth", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/borealis202108_13_600x.webp" },
  { name: "Galaxy Quest", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/orca17_1.webp" },
  { name: "Gold", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/puffin11_2.webp" },
  { name: "Golden Hour", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/scout17_1_600x.webp" },
  { name: "Gold Nugget", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/puffin15_1.webp" },
  { name: "Goose Bay", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/scout20_600x.webp" },
  { name: "Grape", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bigdipper12.webp" },
  { name: "Grape Maiderade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/gnar14_2_600x.webp" },
  { name: "Grassy Lake", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/chief13_1.webp" },
  { name: "Gravy Boat", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/arcticcircle11_2.webp" },
  { name: "Graysocean", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/boy202112_14.jpg" },
  { name: "Green Apple", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/puffin2_11.webp" },
  { name: "Green Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/arcticcircle13_1.webp" },
  { name: "Green Eye Monster", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bonfire15_3.webp" },
  { name: "Green Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/gnar11_600x.webp" },
  { name: "Green Valley", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/kodiak11_1_600x.webp" },
  { name: "Grey BIP BOP", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bonfire23.webp" },
  { name: "Grey Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/arcticcircle15_1_1.webp" },
  { name: "Grey Ghost", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/gorge11.webp" },
  { name: "Grey Purple Splash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/bvm2_14_600x.webp" },
  { name: "Gun Metal Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/06/kayak15_1_600x.webp" },
  { name: "Hania", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/bonfire11_2.webp" },
  { name: "Happy Dragon", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/chief14_9.webp" },
  { name: "Harrison Hurricane", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/cliff16_1_1_600x.webp" },
  { name: "Harrison Hurricane Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/orca12_1.webp" },
  { name: "Hazelnut", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2023/03/otter202302_14-1.jpg" },
  { name: "Hi Andre", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/chief12_11.webp" },
  { name: "Horseshoe Bay", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/avalanche13_1_600x.webp" },
  { name: "Horsehead Nebula", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/akita202112_11.jpg" },
  { name: "Hot Fire Lava", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/bonfire15_1.webp" },
  { name: "Hot Pink", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/puffin12_2.webp" },
  { name: "Hulk Smash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/puffin13a.webp" },
  { name: "Hulk Smash Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/puffin13_2.webp" },
  { name: "Hulk Smash Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/chief14_6.webp" },
  { name: "Hulk Splash Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/avalanche15_1_600x.webp" },
  { name: "Iceberg", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/gnar12_1_600x.webp" },
  { name: "Icy Purple Splash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/puffin12_3.webp" },
  { name: "Incredible Kimmitt", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/wooly2_11.webp" },
  { name: "Indigo", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/kodiak202402_14.jpg" },
  { name: "Indigo Montoya", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/scout13_3_600x.webp" },
  { name: "Intergalactic Hulk Smash Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/chief16_6.webp" },
  { name: "Intergalactic Salamander", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/orca11_4.webp" },
  { name: "Jack Rabbit", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/arcticcircle12_1_1.webp" },
  { name: "Joe vs Return Top Splash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/scout18_600x.jpg" },
  { name: "Latitude 53", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/bonfire14_1.webp" },
  { name: "Lime Sherbet", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/manatee13_2_9125f2b3-a947-4b2e-b2e2-c9c33ba3df0e_600x.webp" },
  { name: "Lost In Space", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/orca16_1.webp" },
  { name: "Maiderade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/puffin2_16_1.webp" },
  { name: "Maiderade Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/blizzard16_1.webp" },
  { name: "Matsuri", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/bvm2-13_600x.webp" },
  { name: "Matsuri Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/scout16_600x.webp" },
  { name: "Matsuri Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/borealis12_1_3_600x.webp" },
  { name: "Milk Shake", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/bigdipper13.webp" },
  { name: "Milkweed", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/manatee15_1_ce6aaa2a-9bd9-4836-895d-7018405b6e91_600x.webp" },
  { name: "Mirage Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/kayak13_1_1_600x.webp" },
  { name: "Midnight Quartz", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/dune202309_11.jpg" },
  { name: "MisChief", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/chief16_5.webp" },
  { name: "Monty Mint Mint Mint", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/chief12_1.webp" },
  { name: "Moose Taffy", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/avalanche11a_600x.webp" },
  { name: "Moss Man", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/scout14_1_600x.webp" },
  { name: "Moss Man Splatter", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/scout15_1_600x.webp" },
  { name: "Mudberry", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/scout15_3_600x.webp" },
  { name: "Mudskipper", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/avalanche13a_600x.webp" },
  { name: "Murky Summertide", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/glacierexpress14.jpg" },
  { name: "Musket", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/chief11_1.webp" },
  { name: "Mystic Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/07/kayak14_1.jpg" },
  { name: "Mystic Lake", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/scout17_600x.webp" },
  { name: "Nebula", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/puffin14_2.webp" },
  { name: "Night Fishing", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/igloo12.webp" },
  { name: "Nightngale", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/puffin15_3.webp" },
  { name: "Night Lava", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/orca16_3.webp" },
  { name: "Ninja Hurdles", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/chief11_6.webp" },
  { name: "Northern Lights", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/chief13.webp" },
  { name: "Ocean Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/manatee11_9d94b8e7-86b6-49dd-ac7f-7b85888ee624_600x.webp" },
  { name: "Orca Edition", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/orca11.webp" },
  { name: "Orpheum Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/compass13_1_600x.webp" },
  { name: "Palli's Puffin", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/puffin17_1.webp" },
  { name: "Party Animal", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/ac12_1.webp" },
  { name: "Peacebone", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/manatee12_1_e656ece9-3d7e-4dec-8965-5fbd615b3407_600x.webp" },
  { name: "Pekka", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/arcticcircle13.webp" },
  { name: "Pete the Purple Squirrel", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/avalanche12_1_600x.webp" },
  { name: "Petr Kavka", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/cliff11_600x.webp" },
  { name: "Pocono", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/manatee13_1_75275a84-d2fd-4666-b8dc-b06c4daa9e89_600x.webp" },
  { name: "Porygoner", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/pickaxe14_1_600x.webp" },
  { name: "Power Up", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/avalanche14_1_600x.webp" },
  { name: "Prickly Pear", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2025/07/dune202309_12.jpg" },
  { name: "Purple Ombre", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/kayak12_1_600x.webp" },
  { name: "Purple Speckle", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/bvm2_11_600x.webp" },
  { name: "Purple Wayfarer", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/manatee12_2_c43955d4-c867-4aef-a9e3-bd4d0aa20f10_600x.webp" },
  { name: "Pyramid Mountain", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/cliff13_1_1_600x.webp" },
  { name: "Rainbow Reef", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/dune20191028_12_600x.webp" },
  { name: "Rainbow Trout", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/scout16_1_600x.webp" },
  { name: "Rafmagn", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/puffin14_3.webp" },
  { name: "Rasta", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/puffin2_12_1.webp" },
  { name: "Red Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/cliff13_600x.webp" },
  { name: "Red White Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/avalanchi12.webp" },
  { name: "Red w/Clear Splash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/sasquatch13_800x.webp" },
  { name: "REWIND", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/chief11_4_1.webp" },
  { name: "Rootbeer Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/puffin11.webp" },
  { name: "Rustoleum", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/orca19.webp" },
  { name: "Sage Green", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/boy202012_11_600x.webp" },
  { name: "Salmon Fade", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/08/manatee16_facbd6e3-5ce3-4e2b-a2fe-10e109b00a87_600x.webp" },
  { name: "Sand", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/kayak15_1_1_600x.webp" },
  { name: "Sarsaparilla", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/borealis202108_11_600x.webp" },
  { name: "Saskatoon Berry", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/arcticcircle11.webp" },
  { name: "Saskatoon Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/cliff16_1_600x.webp" },
  { name: "Scorched Earth", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/orca15_3.webp" },
  { name: "Selvedge Gold", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/ac13.webp" },
  { name: "Shark VS Zombie Beaver", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/avalanche14_2_600x.webp" },
  { name: "Snow Cone", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/pickaxe12_1_600x.webp" },
  { name: "Solid Aqua", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/scout11_1_600x.webp" },
  { name: "Solid Black", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/wooly2_19.webp" },
  { name: "Solid Blue", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/sasquach11.webp" },
  { name: "Solid Brown", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/bonfire11a.webp" },
  { name: "Solid Gold", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/sasquatch12_1.webp" },
  { name: "Solid Green", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/puffin2_12_2.webp" },
  { name: "Solid Gray", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/puffin2_13_2.webp" },
  { name: "Solid Orange", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/sasquach13.webp" },
  { name: "Solid Pink", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/scout13_600x.webp" },
  { name: "Solid Purple", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/metalyeti12.webp" },
  { name: "Solid Red", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/bonfire12_4.webp" },
  { name: "Space Bear", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/gnar16_2_600x.webp" },
  { name: "Space Blizzard", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/cliff11-s_600x.webp" },
  { name: "Space Camo", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/scout12_3_600x.webp" },
  { name: "Space Dragon", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/scout14_3_600x.webp" },
  { name: "Spanish Sunset", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/avalanch17.webp" },
  { name: "Splash Red Silver", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/borealis13_2_2_600x.webp" },
  { name: "Splash Red Yellow", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/gnar16_600x.webp" },
  { name: "Summer Squash", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/orca14_2.webp" },
  { name: "Summertide", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/puffin12_4.webp" },
  { name: "Sunrise Kingdom", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/09/wooly2_12_1.webp" },
  { name: "The Widowmaker", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/10/cliff14.webp" },
  { name: "Tiffany Mint", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/10/borealis11_2_2_600x.webp" },
  { name: "Tiger Beat", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/10/bonfire16_2.webp" },
  { name: "Ultimate Gray", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2023/03/otter202302_13-1.jpg" },
  { name: "Uncola", imageUrl: "https://i0.wp.com/yoyorewind.com/jp/wp-content/uploads/2022/10/orca13_3.webp" },
]

export async function POST() {
  let created = 0
  let skipped = 0

  for (const color of clywColors) {
    try {
      await prisma.yoyoColor.create({
        data: {
          name: color.name,
          imageUrl: color.imageUrl,
          isActive: true,
        },
      })
      created++
    } catch {
      // Color already exists, skip
      skipped++
    }
  }

  return NextResponse.json({
    message: `Seeded ${created} colors, skipped ${skipped} duplicates`,
    total: clywColors.length,
    created,
    skipped,
  })
}
